server:
  port: 8082
spring:
  application:
    name: "registrar-solicitudes-crediYA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
routes:
  paths:
    solicitudes: "/api/v1/solicitudes"
adapters:
  r2dbc:
    host: "${POSTGRES_HOST:postgres}"
    port: "${POSTGRES_PORT:5432}"
    database: "${POSTGRES_DB:solicitudesdb}"
    schema: "public"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:}"
  restconsumer:
    url: "http://localhost:8081/api/v1/usuarios"
    timeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
